// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/interfaces.go -destination=internal/service/mock/mock_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	dto "gastrack/internal/dto"
	model "gastrack/internal/model"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockInviteServicer is a mock of InviteServicer interface.
type MockInviteServicer struct {
	ctrl     *gomock.Controller
	recorder *MockInviteServicerMockRecorder
	isgomock struct{}
}

// MockInviteServicerMockRecorder is the mock recorder for MockInviteServicer.
type MockInviteServicerMockRecorder struct {
	mock *MockInviteServicer
}

// NewMockInviteServicer creates a new mock instance.
func NewMockInviteServicer(ctrl *gomock.Controller) *MockInviteServicer {
	mock := &MockInviteServicer{ctrl: ctrl}
	mock.recorder = &MockInviteServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInviteServicer) EXPECT() *MockInviteServicerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInviteServicer) Create(ctx context.Context, creatorID uuid.UUID, req *dto.CreateInviteRequest) (*dto.InviteCodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, creatorID, req)
	ret0, _ := ret[0].(*dto.InviteCodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInviteServicerMockRecorder) Create(ctx, creatorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInviteServicer)(nil).Create), ctx, creatorID, req)
}

// Delete mocks base method.
func (m *MockInviteServicer) Delete(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInviteServicerMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInviteServicer)(nil).Delete), ctx, id, userID)
}

// GetByCode mocks base method.
func (m *MockInviteServicer) GetByCode(ctx context.Context, code string) (*dto.ValidateInviteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*dto.ValidateInviteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockInviteServicerMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockInviteServicer)(nil).GetByCode), ctx, code)
}

// List mocks base method.
func (m *MockInviteServicer) List(ctx context.Context, userID uuid.UUID) ([]dto.InviteCodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]dto.InviteCodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInviteServicerMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInviteServicer)(nil).List), ctx, userID)
}

// Update mocks base method.
func (m *MockInviteServicer) Update(ctx context.Context, id, userID uuid.UUID, req *dto.UpdateInviteRequest) (*dto.InviteCodeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, userID, req)
	ret0, _ := ret[0].(*dto.InviteCodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockInviteServicerMockRecorder) Update(ctx, id, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInviteServicer)(nil).Update), ctx, id, userID, req)
}

// ValidateAndConsumeInviteCode mocks base method.
func (m *MockInviteServicer) ValidateAndConsumeInviteCode(ctx context.Context, code string, userID uuid.UUID) (*model.InviteCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndConsumeInviteCode", ctx, code, userID)
	ret0, _ := ret[0].(*model.InviteCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndConsumeInviteCode indicates an expected call of ValidateAndConsumeInviteCode.
func (mr *MockInviteServicerMockRecorder) ValidateAndConsumeInviteCode(ctx, code, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndConsumeInviteCode", reflect.TypeOf((*MockInviteServicer)(nil).ValidateAndConsumeInviteCode), ctx, code, userID)
}

// MockNotificationServicer is a mock of NotificationServicer interface.
type MockNotificationServicer struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServicerMockRecorder
	isgomock struct{}
}

// MockNotificationServicerMockRecorder is the mock recorder for MockNotificationServicer.
type MockNotificationServicerMockRecorder struct {
	mock *MockNotificationServicer
}

// NewMockNotificationServicer creates a new mock instance.
func NewMockNotificationServicer(ctrl *gomock.Controller) *MockNotificationServicer {
	mock := &MockNotificationServicer{ctrl: ctrl}
	mock.recorder = &MockNotificationServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationServicer) EXPECT() *MockNotificationServicerMockRecorder {
	return m.recorder
}

// CheckFuelAnomaly mocks base method.
func (m *MockNotificationServicer) CheckFuelAnomaly(ctx context.Context, userID, vehicleID, recordID uuid.UUID, currentEfficiency float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckFuelAnomaly", ctx, userID, vehicleID, recordID, currentEfficiency)
}

// CheckFuelAnomaly indicates an expected call of CheckFuelAnomaly.
func (mr *MockNotificationServicerMockRecorder) CheckFuelAnomaly(ctx, userID, vehicleID, recordID, currentEfficiency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckFuelAnomaly", reflect.TypeOf((*MockNotificationServicer)(nil).CheckFuelAnomaly), ctx, userID, vehicleID, recordID, currentEfficiency)
}

// CheckMaintenanceReminders mocks base method.
func (m *MockNotificationServicer) CheckMaintenanceReminders(ctx context.Context, userID, vehicleID uuid.UUID, currentOdometer float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckMaintenanceReminders", ctx, userID, vehicleID, currentOdometer)
}

// CheckMaintenanceReminders indicates an expected call of CheckMaintenanceReminders.
func (mr *MockNotificationServicerMockRecorder) CheckMaintenanceReminders(ctx, userID, vehicleID, currentOdometer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMaintenanceReminders", reflect.TypeOf((*MockNotificationServicer)(nil).CheckMaintenanceReminders), ctx, userID, vehicleID, currentOdometer)
}

// Delete mocks base method.
func (m *MockNotificationServicer) Delete(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationServicerMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationServicer)(nil).Delete), ctx, id, userID)
}

// List mocks base method.
func (m *MockNotificationServicer) List(ctx context.Context, userID uuid.UUID) ([]dto.NotificationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]dto.NotificationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNotificationServicerMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNotificationServicer)(nil).List), ctx, userID)
}

// MarkAllAsRead mocks base method.
func (m *MockNotificationServicer) MarkAllAsRead(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllAsRead", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllAsRead indicates an expected call of MarkAllAsRead.
func (mr *MockNotificationServicerMockRecorder) MarkAllAsRead(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllAsRead", reflect.TypeOf((*MockNotificationServicer)(nil).MarkAllAsRead), ctx, userID)
}

// MarkAsRead mocks base method.
func (m *MockNotificationServicer) MarkAsRead(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockNotificationServicerMockRecorder) MarkAsRead(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockNotificationServicer)(nil).MarkAsRead), ctx, id, userID)
}

// NotifyInviteUsed mocks base method.
func (m *MockNotificationServicer) NotifyInviteUsed(ctx context.Context, inviteCreatorID uuid.UUID, inviteCode, newUserNickname string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyInviteUsed", ctx, inviteCreatorID, inviteCode, newUserNickname)
}

// NotifyInviteUsed indicates an expected call of NotifyInviteUsed.
func (mr *MockNotificationServicerMockRecorder) NotifyInviteUsed(ctx, inviteCreatorID, inviteCode, newUserNickname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyInviteUsed", reflect.TypeOf((*MockNotificationServicer)(nil).NotifyInviteUsed), ctx, inviteCreatorID, inviteCode, newUserNickname)
}

// UnreadCount mocks base method.
func (m *MockNotificationServicer) UnreadCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnreadCount", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnreadCount indicates an expected call of UnreadCount.
func (mr *MockNotificationServicerMockRecorder) UnreadCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnreadCount", reflect.TypeOf((*MockNotificationServicer)(nil).UnreadCount), ctx, userID)
}
