// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces.go -destination=internal/repository/mock/mock_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gastrack/internal/model"
	repository "gastrack/internal/repository"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepo) Create(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepoMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepo)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockUserRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepo)(nil).Delete), ctx, id)
}

// ExistsByEmail mocks base method.
func (m *MockUserRepo) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockUserRepoMockRecorder) ExistsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockUserRepo)(nil).ExistsByEmail), ctx, email)
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockUserRepo) GetByIDs(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].(map[uuid.UUID]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockUserRepoMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockUserRepo)(nil).GetByIDs), ctx, ids)
}

// Update mocks base method.
func (m *MockUserRepo) Update(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepoMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepo)(nil).Update), ctx, user)
}

// UpdateFields mocks base method.
func (m *MockUserRepo) UpdateFields(ctx context.Context, id uuid.UUID, fields map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFields", ctx, id, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFields indicates an expected call of UpdateFields.
func (mr *MockUserRepoMockRecorder) UpdateFields(ctx, id, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFields", reflect.TypeOf((*MockUserRepo)(nil).UpdateFields), ctx, id, fields)
}

// UpdateLastLogin mocks base method.
func (m *MockUserRepo) UpdateLastLogin(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockUserRepoMockRecorder) UpdateLastLogin(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockUserRepo)(nil).UpdateLastLogin), ctx, id)
}

// MockVehicleRepo is a mock of VehicleRepo interface.
type MockVehicleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleRepoMockRecorder
	isgomock struct{}
}

// MockVehicleRepoMockRecorder is the mock recorder for MockVehicleRepo.
type MockVehicleRepoMockRecorder struct {
	mock *MockVehicleRepo
}

// NewMockVehicleRepo creates a new mock instance.
func NewMockVehicleRepo(ctrl *gomock.Controller) *MockVehicleRepo {
	mock := &MockVehicleRepo{ctrl: ctrl}
	mock.recorder = &MockVehicleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleRepo) EXPECT() *MockVehicleRepoMockRecorder {
	return m.recorder
}

// ClearDefault mocks base method.
func (m *MockVehicleRepo) ClearDefault(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDefault", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearDefault indicates an expected call of ClearDefault.
func (mr *MockVehicleRepoMockRecorder) ClearDefault(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDefault", reflect.TypeOf((*MockVehicleRepo)(nil).ClearDefault), ctx, userID)
}

// ClearDefaultTx mocks base method.
func (m *MockVehicleRepo) ClearDefaultTx(ctx context.Context, tx *gorm.DB, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDefaultTx", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearDefaultTx indicates an expected call of ClearDefaultTx.
func (mr *MockVehicleRepoMockRecorder) ClearDefaultTx(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDefaultTx", reflect.TypeOf((*MockVehicleRepo)(nil).ClearDefaultTx), ctx, tx, userID)
}

// CountByUser mocks base method.
func (m *MockVehicleRepo) CountByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUser", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUser indicates an expected call of CountByUser.
func (mr *MockVehicleRepoMockRecorder) CountByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUser", reflect.TypeOf((*MockVehicleRepo)(nil).CountByUser), ctx, userID)
}

// Create mocks base method.
func (m *MockVehicleRepo) Create(ctx context.Context, vehicle *model.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, vehicle)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVehicleRepoMockRecorder) Create(ctx, vehicle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVehicleRepo)(nil).Create), ctx, vehicle)
}

// CreateTx mocks base method.
func (m *MockVehicleRepo) CreateTx(ctx context.Context, tx *gorm.DB, vehicle *model.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTx", ctx, tx, vehicle)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTx indicates an expected call of CreateTx.
func (mr *MockVehicleRepoMockRecorder) CreateTx(ctx, tx, vehicle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTx", reflect.TypeOf((*MockVehicleRepo)(nil).CreateTx), ctx, tx, vehicle)
}

// DB mocks base method.
func (m *MockVehicleRepo) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockVehicleRepoMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockVehicleRepo)(nil).DB))
}

// Delete mocks base method.
func (m *MockVehicleRepo) Delete(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVehicleRepoMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVehicleRepo)(nil).Delete), ctx, id, userID)
}

// GetByID mocks base method.
func (m *MockVehicleRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVehicleRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVehicleRepo)(nil).GetByID), ctx, id)
}

// GetByIDAndUser mocks base method.
func (m *MockVehicleRepo) GetByIDAndUser(ctx context.Context, id, userID uuid.UUID) (*model.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDAndUser", ctx, id, userID)
	ret0, _ := ret[0].(*model.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDAndUser indicates an expected call of GetByIDAndUser.
func (mr *MockVehicleRepoMockRecorder) GetByIDAndUser(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDAndUser", reflect.TypeOf((*MockVehicleRepo)(nil).GetByIDAndUser), ctx, id, userID)
}

// GetByIDs mocks base method.
func (m *MockVehicleRepo) GetByIDs(ctx context.Context, ids []uuid.UUID) (map[uuid.UUID]*model.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].(map[uuid.UUID]*model.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockVehicleRepoMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockVehicleRepo)(nil).GetByIDs), ctx, ids)
}

// ListByUser mocks base method.
func (m *MockVehicleRepo) ListByUser(ctx context.Context, userID uuid.UUID, includeArchived bool) ([]model.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, includeArchived)
	ret0, _ := ret[0].([]model.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockVehicleRepoMockRecorder) ListByUser(ctx, userID, includeArchived any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockVehicleRepo)(nil).ListByUser), ctx, userID, includeArchived)
}

// Update mocks base method.
func (m *MockVehicleRepo) Update(ctx context.Context, vehicle *model.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, vehicle)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVehicleRepoMockRecorder) Update(ctx, vehicle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVehicleRepo)(nil).Update), ctx, vehicle)
}

// UpdateTx mocks base method.
func (m *MockVehicleRepo) UpdateTx(ctx context.Context, tx *gorm.DB, vehicle *model.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTx", ctx, tx, vehicle)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTx indicates an expected call of UpdateTx.
func (mr *MockVehicleRepoMockRecorder) UpdateTx(ctx, tx, vehicle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTx", reflect.TypeOf((*MockVehicleRepo)(nil).UpdateTx), ctx, tx, vehicle)
}

// MockFuelRecordRepo is a mock of FuelRecordRepo interface.
type MockFuelRecordRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFuelRecordRepoMockRecorder
	isgomock struct{}
}

// MockFuelRecordRepoMockRecorder is the mock recorder for MockFuelRecordRepo.
type MockFuelRecordRepoMockRecorder struct {
	mock *MockFuelRecordRepo
}

// NewMockFuelRecordRepo creates a new mock instance.
func NewMockFuelRecordRepo(ctrl *gomock.Controller) *MockFuelRecordRepo {
	mock := &MockFuelRecordRepo{ctrl: ctrl}
	mock.recorder = &MockFuelRecordRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFuelRecordRepo) EXPECT() *MockFuelRecordRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFuelRecordRepo) Create(ctx context.Context, record *model.FuelRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFuelRecordRepoMockRecorder) Create(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFuelRecordRepo)(nil).Create), ctx, record)
}

// Delete mocks base method.
func (m *MockFuelRecordRepo) Delete(ctx context.Context, id, vehicleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, vehicleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFuelRecordRepoMockRecorder) Delete(ctx, id, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFuelRecordRepo)(nil).Delete), ctx, id, vehicleID)
}

// GetByID mocks base method.
func (m *MockFuelRecordRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.FuelRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.FuelRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFuelRecordRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetByID), ctx, id)
}

// GetByIDAndVehicle mocks base method.
func (m *MockFuelRecordRepo) GetByIDAndVehicle(ctx context.Context, id, vehicleID uuid.UUID) (*model.FuelRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDAndVehicle", ctx, id, vehicleID)
	ret0, _ := ret[0].(*model.FuelRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDAndVehicle indicates an expected call of GetByIDAndVehicle.
func (mr *MockFuelRecordRepoMockRecorder) GetByIDAndVehicle(ctx, id, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDAndVehicle", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetByIDAndVehicle), ctx, id, vehicleID)
}

// GetCostByCurrency mocks base method.
func (m *MockFuelRecordRepo) GetCostByCurrency(ctx context.Context, vehicleID uuid.UUID) ([]repository.CostByCurrencyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCostByCurrency", ctx, vehicleID)
	ret0, _ := ret[0].([]repository.CostByCurrencyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCostByCurrency indicates an expected call of GetCostByCurrency.
func (mr *MockFuelRecordRepoMockRecorder) GetCostByCurrency(ctx, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCostByCurrency", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetCostByCurrency), ctx, vehicleID)
}

// GetDistinctStationNames mocks base method.
func (m *MockFuelRecordRepo) GetDistinctStationNames(ctx context.Context, userID uuid.UUID, vehicleID *uuid.UUID, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctStationNames", ctx, userID, vehicleID, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctStationNames indicates an expected call of GetDistinctStationNames.
func (mr *MockFuelRecordRepoMockRecorder) GetDistinctStationNames(ctx, userID, vehicleID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctStationNames", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetDistinctStationNames), ctx, userID, vehicleID, limit)
}

// GetEfficiencyTrend mocks base method.
func (m *MockFuelRecordRepo) GetEfficiencyTrend(ctx context.Context, vehicleID uuid.UUID, limit int) ([]model.FuelRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEfficiencyTrend", ctx, vehicleID, limit)
	ret0, _ := ret[0].([]model.FuelRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEfficiencyTrend indicates an expected call of GetEfficiencyTrend.
func (mr *MockFuelRecordRepoMockRecorder) GetEfficiencyTrend(ctx, vehicleID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEfficiencyTrend", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetEfficiencyTrend), ctx, vehicleID, limit)
}

// GetExpensesByMonth mocks base method.
func (m *MockFuelRecordRepo) GetExpensesByMonth(ctx context.Context, userID uuid.UUID, vehicleID *uuid.UUID, start, end time.Time) ([]repository.ExpenseByPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpensesByMonth", ctx, userID, vehicleID, start, end)
	ret0, _ := ret[0].([]repository.ExpenseByPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpensesByMonth indicates an expected call of GetExpensesByMonth.
func (mr *MockFuelRecordRepoMockRecorder) GetExpensesByMonth(ctx, userID, vehicleID, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpensesByMonth", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetExpensesByMonth), ctx, userID, vehicleID, start, end)
}

// GetMultiVehicleCostByCurrency mocks base method.
func (m *MockFuelRecordRepo) GetMultiVehicleCostByCurrency(ctx context.Context, vehicleIDs []uuid.UUID) (map[uuid.UUID][]repository.CostByCurrencyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMultiVehicleCostByCurrency", ctx, vehicleIDs)
	ret0, _ := ret[0].(map[uuid.UUID][]repository.CostByCurrencyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMultiVehicleCostByCurrency indicates an expected call of GetMultiVehicleCostByCurrency.
func (mr *MockFuelRecordRepoMockRecorder) GetMultiVehicleCostByCurrency(ctx, vehicleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMultiVehicleCostByCurrency", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetMultiVehicleCostByCurrency), ctx, vehicleIDs)
}

// GetMultiVehicleStats mocks base method.
func (m *MockFuelRecordRepo) GetMultiVehicleStats(ctx context.Context, vehicleIDs []uuid.UUID) (map[uuid.UUID]*repository.MultiVehicleStatsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMultiVehicleStats", ctx, vehicleIDs)
	ret0, _ := ret[0].(map[uuid.UUID]*repository.MultiVehicleStatsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMultiVehicleStats indicates an expected call of GetMultiVehicleStats.
func (mr *MockFuelRecordRepoMockRecorder) GetMultiVehicleStats(ctx, vehicleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMultiVehicleStats", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetMultiVehicleStats), ctx, vehicleIDs)
}

// GetPreviousRecord mocks base method.
func (m *MockFuelRecordRepo) GetPreviousRecord(ctx context.Context, vehicleID uuid.UUID, beforeDate time.Time) (*model.FuelRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreviousRecord", ctx, vehicleID, beforeDate)
	ret0, _ := ret[0].(*model.FuelRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreviousRecord indicates an expected call of GetPreviousRecord.
func (mr *MockFuelRecordRepoMockRecorder) GetPreviousRecord(ctx, vehicleID, beforeDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreviousRecord", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetPreviousRecord), ctx, vehicleID, beforeDate)
}

// GetStatsByMonth mocks base method.
func (m *MockFuelRecordRepo) GetStatsByMonth(ctx context.Context, vehicleID uuid.UUID, year int) ([]repository.PeriodStatsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatsByMonth", ctx, vehicleID, year)
	ret0, _ := ret[0].([]repository.PeriodStatsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatsByMonth indicates an expected call of GetStatsByMonth.
func (mr *MockFuelRecordRepoMockRecorder) GetStatsByMonth(ctx, vehicleID, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatsByMonth", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetStatsByMonth), ctx, vehicleID, year)
}

// GetStatsByYear mocks base method.
func (m *MockFuelRecordRepo) GetStatsByYear(ctx context.Context, vehicleID uuid.UUID) ([]repository.PeriodStatsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatsByYear", ctx, vehicleID)
	ret0, _ := ret[0].([]repository.PeriodStatsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatsByYear indicates an expected call of GetStatsByYear.
func (mr *MockFuelRecordRepoMockRecorder) GetStatsByYear(ctx, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatsByYear", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetStatsByYear), ctx, vehicleID)
}

// GetVehicleStats mocks base method.
func (m *MockFuelRecordRepo) GetVehicleStats(ctx context.Context, vehicleID uuid.UUID) (*repository.StatsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVehicleStats", ctx, vehicleID)
	ret0, _ := ret[0].(*repository.StatsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVehicleStats indicates an expected call of GetVehicleStats.
func (mr *MockFuelRecordRepoMockRecorder) GetVehicleStats(ctx, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVehicleStats", reflect.TypeOf((*MockFuelRecordRepo)(nil).GetVehicleStats), ctx, vehicleID)
}

// ListAllByUser mocks base method.
func (m *MockFuelRecordRepo) ListAllByUser(ctx context.Context, userID uuid.UUID) ([]model.FuelRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllByUser", ctx, userID)
	ret0, _ := ret[0].([]model.FuelRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllByUser indicates an expected call of ListAllByUser.
func (mr *MockFuelRecordRepoMockRecorder) ListAllByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllByUser", reflect.TypeOf((*MockFuelRecordRepo)(nil).ListAllByUser), ctx, userID)
}

// ListByVehicle mocks base method.
func (m *MockFuelRecordRepo) ListByVehicle(ctx context.Context, vehicleID uuid.UUID, page, pageSize int) ([]model.FuelRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVehicle", ctx, vehicleID, page, pageSize)
	ret0, _ := ret[0].([]model.FuelRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByVehicle indicates an expected call of ListByVehicle.
func (mr *MockFuelRecordRepoMockRecorder) ListByVehicle(ctx, vehicleID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVehicle", reflect.TypeOf((*MockFuelRecordRepo)(nil).ListByVehicle), ctx, vehicleID, page, pageSize)
}

// Update mocks base method.
func (m *MockFuelRecordRepo) Update(ctx context.Context, record *model.FuelRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFuelRecordRepoMockRecorder) Update(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFuelRecordRepo)(nil).Update), ctx, record)
}

// MockGroupRepo is a mock of GroupRepo interface.
type MockGroupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepoMockRecorder
	isgomock struct{}
}

// MockGroupRepoMockRecorder is the mock recorder for MockGroupRepo.
type MockGroupRepoMockRecorder struct {
	mock *MockGroupRepo
}

// NewMockGroupRepo creates a new mock instance.
func NewMockGroupRepo(ctrl *gomock.Controller) *MockGroupRepo {
	mock := &MockGroupRepo{ctrl: ctrl}
	mock.recorder = &MockGroupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepo) EXPECT() *MockGroupRepoMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockGroupRepo) AddMember(ctx context.Context, member *model.GroupMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockGroupRepoMockRecorder) AddMember(ctx, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockGroupRepo)(nil).AddMember), ctx, member)
}

// CountMembers mocks base method.
func (m *MockGroupRepo) CountMembers(ctx context.Context, groupID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMembers", ctx, groupID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMembers indicates an expected call of CountMembers.
func (mr *MockGroupRepoMockRecorder) CountMembers(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMembers", reflect.TypeOf((*MockGroupRepo)(nil).CountMembers), ctx, groupID)
}

// Create mocks base method.
func (m *MockGroupRepo) Create(ctx context.Context, group *model.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupRepoMockRecorder) Create(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupRepo)(nil).Create), ctx, group)
}

// CreateSharedVehicle mocks base method.
func (m *MockGroupRepo) CreateSharedVehicle(ctx context.Context, sv *model.SharedVehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSharedVehicle", ctx, sv)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSharedVehicle indicates an expected call of CreateSharedVehicle.
func (mr *MockGroupRepoMockRecorder) CreateSharedVehicle(ctx, sv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSharedVehicle", reflect.TypeOf((*MockGroupRepo)(nil).CreateSharedVehicle), ctx, sv)
}

// DB mocks base method.
func (m *MockGroupRepo) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockGroupRepoMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockGroupRepo)(nil).DB))
}

// Delete mocks base method.
func (m *MockGroupRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupRepo)(nil).Delete), ctx, id)
}

// DeleteSharedVehicle mocks base method.
func (m *MockGroupRepo) DeleteSharedVehicle(ctx context.Context, groupID, vehicleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSharedVehicle", ctx, groupID, vehicleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSharedVehicle indicates an expected call of DeleteSharedVehicle.
func (mr *MockGroupRepoMockRecorder) DeleteSharedVehicle(ctx, groupID, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSharedVehicle", reflect.TypeOf((*MockGroupRepo)(nil).DeleteSharedVehicle), ctx, groupID, vehicleID)
}

// ExistsByInviteCode mocks base method.
func (m *MockGroupRepo) ExistsByInviteCode(ctx context.Context, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByInviteCode", ctx, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByInviteCode indicates an expected call of ExistsByInviteCode.
func (mr *MockGroupRepoMockRecorder) ExistsByInviteCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByInviteCode", reflect.TypeOf((*MockGroupRepo)(nil).ExistsByInviteCode), ctx, code)
}

// ExistsSharedVehicle mocks base method.
func (m *MockGroupRepo) ExistsSharedVehicle(ctx context.Context, groupID, vehicleID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsSharedVehicle", ctx, groupID, vehicleID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsSharedVehicle indicates an expected call of ExistsSharedVehicle.
func (mr *MockGroupRepoMockRecorder) ExistsSharedVehicle(ctx, groupID, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsSharedVehicle", reflect.TypeOf((*MockGroupRepo)(nil).ExistsSharedVehicle), ctx, groupID, vehicleID)
}

// GetByID mocks base method.
func (m *MockGroupRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGroupRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGroupRepo)(nil).GetByID), ctx, id)
}

// GetByIDWithMembers mocks base method.
func (m *MockGroupRepo) GetByIDWithMembers(ctx context.Context, id uuid.UUID) (*model.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDWithMembers", ctx, id)
	ret0, _ := ret[0].(*model.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDWithMembers indicates an expected call of GetByIDWithMembers.
func (mr *MockGroupRepoMockRecorder) GetByIDWithMembers(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDWithMembers", reflect.TypeOf((*MockGroupRepo)(nil).GetByIDWithMembers), ctx, id)
}

// GetByInviteCode mocks base method.
func (m *MockGroupRepo) GetByInviteCode(ctx context.Context, code string) (*model.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInviteCode", ctx, code)
	ret0, _ := ret[0].(*model.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInviteCode indicates an expected call of GetByInviteCode.
func (mr *MockGroupRepoMockRecorder) GetByInviteCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInviteCode", reflect.TypeOf((*MockGroupRepo)(nil).GetByInviteCode), ctx, code)
}

// GetGroupExpenseByMonth mocks base method.
func (m *MockGroupRepo) GetGroupExpenseByMonth(ctx context.Context, groupID uuid.UUID, year int) ([]repository.GroupExpenseRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupExpenseByMonth", ctx, groupID, year)
	ret0, _ := ret[0].([]repository.GroupExpenseRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupExpenseByMonth indicates an expected call of GetGroupExpenseByMonth.
func (mr *MockGroupRepoMockRecorder) GetGroupExpenseByMonth(ctx, groupID, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupExpenseByMonth", reflect.TypeOf((*MockGroupRepo)(nil).GetGroupExpenseByMonth), ctx, groupID, year)
}

// GetGroupExpenseByYear mocks base method.
func (m *MockGroupRepo) GetGroupExpenseByYear(ctx context.Context, groupID uuid.UUID) ([]repository.GroupExpenseRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupExpenseByYear", ctx, groupID)
	ret0, _ := ret[0].([]repository.GroupExpenseRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupExpenseByYear indicates an expected call of GetGroupExpenseByYear.
func (mr *MockGroupRepoMockRecorder) GetGroupExpenseByYear(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupExpenseByYear", reflect.TypeOf((*MockGroupRepo)(nil).GetGroupExpenseByYear), ctx, groupID)
}

// GetGroupStationStats mocks base method.
func (m *MockGroupRepo) GetGroupStationStats(ctx context.Context, groupID uuid.UUID, months int, fuelGrade, sortBy string) ([]repository.StationStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupStationStats", ctx, groupID, months, fuelGrade, sortBy)
	ret0, _ := ret[0].([]repository.StationStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupStationStats indicates an expected call of GetGroupStationStats.
func (mr *MockGroupRepoMockRecorder) GetGroupStationStats(ctx, groupID, months, fuelGrade, sortBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupStationStats", reflect.TypeOf((*MockGroupRepo)(nil).GetGroupStationStats), ctx, groupID, months, fuelGrade, sortBy)
}

// GetGroupVehicleSummary mocks base method.
func (m *MockGroupRepo) GetGroupVehicleSummary(ctx context.Context, groupID uuid.UUID) ([]repository.VehicleSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupVehicleSummary", ctx, groupID)
	ret0, _ := ret[0].([]repository.VehicleSummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupVehicleSummary indicates an expected call of GetGroupVehicleSummary.
func (mr *MockGroupRepoMockRecorder) GetGroupVehicleSummary(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupVehicleSummary", reflect.TypeOf((*MockGroupRepo)(nil).GetGroupVehicleSummary), ctx, groupID)
}

// GetLeaderboard mocks base method.
func (m *MockGroupRepo) GetLeaderboard(ctx context.Context, groupID uuid.UUID, metric string, startDate, endDate time.Time) ([]repository.LeaderboardRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaderboard", ctx, groupID, metric, startDate, endDate)
	ret0, _ := ret[0].([]repository.LeaderboardRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeaderboard indicates an expected call of GetLeaderboard.
func (mr *MockGroupRepoMockRecorder) GetLeaderboard(ctx, groupID, metric, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaderboard", reflect.TypeOf((*MockGroupRepo)(nil).GetLeaderboard), ctx, groupID, metric, startDate, endDate)
}

// GetMember mocks base method.
func (m *MockGroupRepo) GetMember(ctx context.Context, groupID, userID uuid.UUID) (*model.GroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMember", ctx, groupID, userID)
	ret0, _ := ret[0].(*model.GroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockGroupRepoMockRecorder) GetMember(ctx, groupID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockGroupRepo)(nil).GetMember), ctx, groupID, userID)
}

// GetSharedVehicle mocks base method.
func (m *MockGroupRepo) GetSharedVehicle(ctx context.Context, groupID, vehicleID uuid.UUID) (*model.SharedVehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharedVehicle", ctx, groupID, vehicleID)
	ret0, _ := ret[0].(*model.SharedVehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSharedVehicle indicates an expected call of GetSharedVehicle.
func (mr *MockGroupRepoMockRecorder) GetSharedVehicle(ctx, groupID, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedVehicle", reflect.TypeOf((*MockGroupRepo)(nil).GetSharedVehicle), ctx, groupID, vehicleID)
}

// GetStationFuelGrades mocks base method.
func (m *MockGroupRepo) GetStationFuelGrades(ctx context.Context, groupID uuid.UUID, stationNames []string, months int) ([]repository.StationFuelGradeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStationFuelGrades", ctx, groupID, stationNames, months)
	ret0, _ := ret[0].([]repository.StationFuelGradeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStationFuelGrades indicates an expected call of GetStationFuelGrades.
func (mr *MockGroupRepoMockRecorder) GetStationFuelGrades(ctx, groupID, stationNames, months any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStationFuelGrades", reflect.TypeOf((*MockGroupRepo)(nil).GetStationFuelGrades), ctx, groupID, stationNames, months)
}

// GetStationLatestPrices mocks base method.
func (m *MockGroupRepo) GetStationLatestPrices(ctx context.Context, groupID uuid.UUID, stationNames []string, months int) ([]repository.StationLatestPriceRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStationLatestPrices", ctx, groupID, stationNames, months)
	ret0, _ := ret[0].([]repository.StationLatestPriceRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStationLatestPrices indicates an expected call of GetStationLatestPrices.
func (mr *MockGroupRepoMockRecorder) GetStationLatestPrices(ctx, groupID, stationNames, months any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStationLatestPrices", reflect.TypeOf((*MockGroupRepo)(nil).GetStationLatestPrices), ctx, groupID, stationNames, months)
}

// GetStationVisitors mocks base method.
func (m *MockGroupRepo) GetStationVisitors(ctx context.Context, groupID uuid.UUID, stationNames []string, months int) ([]repository.StationVisitorRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStationVisitors", ctx, groupID, stationNames, months)
	ret0, _ := ret[0].([]repository.StationVisitorRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStationVisitors indicates an expected call of GetStationVisitors.
func (mr *MockGroupRepoMockRecorder) GetStationVisitors(ctx, groupID, stationNames, months any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStationVisitors", reflect.TypeOf((*MockGroupRepo)(nil).GetStationVisitors), ctx, groupID, stationNames, months)
}

// IsVehicleSharedToUser mocks base method.
func (m *MockGroupRepo) IsVehicleSharedToUser(ctx context.Context, vehicleID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsVehicleSharedToUser", ctx, vehicleID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsVehicleSharedToUser indicates an expected call of IsVehicleSharedToUser.
func (mr *MockGroupRepoMockRecorder) IsVehicleSharedToUser(ctx, vehicleID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsVehicleSharedToUser", reflect.TypeOf((*MockGroupRepo)(nil).IsVehicleSharedToUser), ctx, vehicleID, userID)
}

// JoinGroupByInviteCode mocks base method.
func (m *MockGroupRepo) JoinGroupByInviteCode(ctx context.Context, code string, userID uuid.UUID) (*model.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinGroupByInviteCode", ctx, code, userID)
	ret0, _ := ret[0].(*model.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinGroupByInviteCode indicates an expected call of JoinGroupByInviteCode.
func (mr *MockGroupRepoMockRecorder) JoinGroupByInviteCode(ctx, code, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinGroupByInviteCode", reflect.TypeOf((*MockGroupRepo)(nil).JoinGroupByInviteCode), ctx, code, userID)
}

// ListGroupsByUser mocks base method.
func (m *MockGroupRepo) ListGroupsByUser(ctx context.Context, userID uuid.UUID) ([]model.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupsByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupsByUser indicates an expected call of ListGroupsByUser.
func (mr *MockGroupRepoMockRecorder) ListGroupsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupsByUser", reflect.TypeOf((*MockGroupRepo)(nil).ListGroupsByUser), ctx, userID)
}

// ListMembers mocks base method.
func (m *MockGroupRepo) ListMembers(ctx context.Context, groupID uuid.UUID) ([]model.GroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, groupID)
	ret0, _ := ret[0].([]model.GroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockGroupRepoMockRecorder) ListMembers(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockGroupRepo)(nil).ListMembers), ctx, groupID)
}

// ListMembershipsByUser mocks base method.
func (m *MockGroupRepo) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]model.GroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembershipsByUser", ctx, userID)
	ret0, _ := ret[0].([]model.GroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembershipsByUser indicates an expected call of ListMembershipsByUser.
func (mr *MockGroupRepoMockRecorder) ListMembershipsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembershipsByUser", reflect.TypeOf((*MockGroupRepo)(nil).ListMembershipsByUser), ctx, userID)
}

// ListSharedVehiclesByGroup mocks base method.
func (m *MockGroupRepo) ListSharedVehiclesByGroup(ctx context.Context, groupID uuid.UUID) ([]model.SharedVehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSharedVehiclesByGroup", ctx, groupID)
	ret0, _ := ret[0].([]model.SharedVehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSharedVehiclesByGroup indicates an expected call of ListSharedVehiclesByGroup.
func (mr *MockGroupRepoMockRecorder) ListSharedVehiclesByGroup(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSharedVehiclesByGroup", reflect.TypeOf((*MockGroupRepo)(nil).ListSharedVehiclesByGroup), ctx, groupID)
}

// ListSharedVehiclesByUser mocks base method.
func (m *MockGroupRepo) ListSharedVehiclesByUser(ctx context.Context, userID uuid.UUID) ([]model.SharedVehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSharedVehiclesByUser", ctx, userID)
	ret0, _ := ret[0].([]model.SharedVehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSharedVehiclesByUser indicates an expected call of ListSharedVehiclesByUser.
func (mr *MockGroupRepoMockRecorder) ListSharedVehiclesByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSharedVehiclesByUser", reflect.TypeOf((*MockGroupRepo)(nil).ListSharedVehiclesByUser), ctx, userID)
}

// ListSharedVehiclesForUser mocks base method.
func (m *MockGroupRepo) ListSharedVehiclesForUser(ctx context.Context, userID uuid.UUID) ([]repository.SharedVehicleWithGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSharedVehiclesForUser", ctx, userID)
	ret0, _ := ret[0].([]repository.SharedVehicleWithGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSharedVehiclesForUser indicates an expected call of ListSharedVehiclesForUser.
func (mr *MockGroupRepoMockRecorder) ListSharedVehiclesForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSharedVehiclesForUser", reflect.TypeOf((*MockGroupRepo)(nil).ListSharedVehiclesForUser), ctx, userID)
}

// RemoveMember mocks base method.
func (m *MockGroupRepo) RemoveMember(ctx context.Context, groupID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, groupID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockGroupRepoMockRecorder) RemoveMember(ctx, groupID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockGroupRepo)(nil).RemoveMember), ctx, groupID, userID)
}

// Update mocks base method.
func (m *MockGroupRepo) Update(ctx context.Context, group *model.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGroupRepoMockRecorder) Update(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupRepo)(nil).Update), ctx, group)
}

// UpdateMemberRole mocks base method.
func (m *MockGroupRepo) UpdateMemberRole(ctx context.Context, groupID, userID uuid.UUID, role model.GroupRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRole", ctx, groupID, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberRole indicates an expected call of UpdateMemberRole.
func (mr *MockGroupRepoMockRecorder) UpdateMemberRole(ctx, groupID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRole", reflect.TypeOf((*MockGroupRepo)(nil).UpdateMemberRole), ctx, groupID, userID, role)
}

// MockExpenseRecordRepo is a mock of ExpenseRecordRepo interface.
type MockExpenseRecordRepo struct {
	ctrl     *gomock.Controller
	recorder *MockExpenseRecordRepoMockRecorder
	isgomock struct{}
}

// MockExpenseRecordRepoMockRecorder is the mock recorder for MockExpenseRecordRepo.
type MockExpenseRecordRepoMockRecorder struct {
	mock *MockExpenseRecordRepo
}

// NewMockExpenseRecordRepo creates a new mock instance.
func NewMockExpenseRecordRepo(ctrl *gomock.Controller) *MockExpenseRecordRepo {
	mock := &MockExpenseRecordRepo{ctrl: ctrl}
	mock.recorder = &MockExpenseRecordRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpenseRecordRepo) EXPECT() *MockExpenseRecordRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExpenseRecordRepo) Create(ctx context.Context, record *model.ExpenseRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockExpenseRecordRepoMockRecorder) Create(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExpenseRecordRepo)(nil).Create), ctx, record)
}

// Delete mocks base method.
func (m *MockExpenseRecordRepo) Delete(ctx context.Context, id, vehicleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, vehicleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExpenseRecordRepoMockRecorder) Delete(ctx, id, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExpenseRecordRepo)(nil).Delete), ctx, id, vehicleID)
}

// GetBreakdownByCategory mocks base method.
func (m *MockExpenseRecordRepo) GetBreakdownByCategory(ctx context.Context, vehicleID uuid.UUID) ([]repository.ExpenseStatsByCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBreakdownByCategory", ctx, vehicleID)
	ret0, _ := ret[0].([]repository.ExpenseStatsByCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBreakdownByCategory indicates an expected call of GetBreakdownByCategory.
func (mr *MockExpenseRecordRepoMockRecorder) GetBreakdownByCategory(ctx, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBreakdownByCategory", reflect.TypeOf((*MockExpenseRecordRepo)(nil).GetBreakdownByCategory), ctx, vehicleID)
}

// GetByID mocks base method.
func (m *MockExpenseRecordRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.ExpenseRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.ExpenseRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockExpenseRecordRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockExpenseRecordRepo)(nil).GetByID), ctx, id)
}

// GetByIDAndVehicle mocks base method.
func (m *MockExpenseRecordRepo) GetByIDAndVehicle(ctx context.Context, id, vehicleID uuid.UUID) (*model.ExpenseRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDAndVehicle", ctx, id, vehicleID)
	ret0, _ := ret[0].(*model.ExpenseRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDAndVehicle indicates an expected call of GetByIDAndVehicle.
func (mr *MockExpenseRecordRepoMockRecorder) GetByIDAndVehicle(ctx, id, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDAndVehicle", reflect.TypeOf((*MockExpenseRecordRepo)(nil).GetByIDAndVehicle), ctx, id, vehicleID)
}

// GetDistinctVendorNames mocks base method.
func (m *MockExpenseRecordRepo) GetDistinctVendorNames(ctx context.Context, userID uuid.UUID, vehicleID *uuid.UUID, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctVendorNames", ctx, userID, vehicleID, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctVendorNames indicates an expected call of GetDistinctVendorNames.
func (mr *MockExpenseRecordRepoMockRecorder) GetDistinctVendorNames(ctx, userID, vehicleID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctVendorNames", reflect.TypeOf((*MockExpenseRecordRepo)(nil).GetDistinctVendorNames), ctx, userID, vehicleID, limit)
}

// GetLast30DaysTotal mocks base method.
func (m *MockExpenseRecordRepo) GetLast30DaysTotal(ctx context.Context, vehicleID uuid.UUID) (float64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLast30DaysTotal", ctx, vehicleID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLast30DaysTotal indicates an expected call of GetLast30DaysTotal.
func (mr *MockExpenseRecordRepoMockRecorder) GetLast30DaysTotal(ctx, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLast30DaysTotal", reflect.TypeOf((*MockExpenseRecordRepo)(nil).GetLast30DaysTotal), ctx, vehicleID)
}

// GetMonthlyTrend mocks base method.
func (m *MockExpenseRecordRepo) GetMonthlyTrend(ctx context.Context, vehicleID uuid.UUID) ([]repository.ExpenseStatsByMonth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlyTrend", ctx, vehicleID)
	ret0, _ := ret[0].([]repository.ExpenseStatsByMonth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlyTrend indicates an expected call of GetMonthlyTrend.
func (mr *MockExpenseRecordRepoMockRecorder) GetMonthlyTrend(ctx, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlyTrend", reflect.TypeOf((*MockExpenseRecordRepo)(nil).GetMonthlyTrend), ctx, vehicleID)
}

// GetTotalRecords mocks base method.
func (m *MockExpenseRecordRepo) GetTotalRecords(ctx context.Context, vehicleID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalRecords", ctx, vehicleID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalRecords indicates an expected call of GetTotalRecords.
func (mr *MockExpenseRecordRepoMockRecorder) GetTotalRecords(ctx, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalRecords", reflect.TypeOf((*MockExpenseRecordRepo)(nil).GetTotalRecords), ctx, vehicleID)
}

// GetTotalsByCurrency mocks base method.
func (m *MockExpenseRecordRepo) GetTotalsByCurrency(ctx context.Context, vehicleID uuid.UUID) ([]repository.ExpenseStatsByCurrency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalsByCurrency", ctx, vehicleID)
	ret0, _ := ret[0].([]repository.ExpenseStatsByCurrency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalsByCurrency indicates an expected call of GetTotalsByCurrency.
func (mr *MockExpenseRecordRepoMockRecorder) GetTotalsByCurrency(ctx, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalsByCurrency", reflect.TypeOf((*MockExpenseRecordRepo)(nil).GetTotalsByCurrency), ctx, vehicleID)
}

// ListAllByUser mocks base method.
func (m *MockExpenseRecordRepo) ListAllByUser(ctx context.Context, userID uuid.UUID) ([]model.ExpenseRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllByUser", ctx, userID)
	ret0, _ := ret[0].([]model.ExpenseRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllByUser indicates an expected call of ListAllByUser.
func (mr *MockExpenseRecordRepoMockRecorder) ListAllByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllByUser", reflect.TypeOf((*MockExpenseRecordRepo)(nil).ListAllByUser), ctx, userID)
}

// ListByVehicle mocks base method.
func (m *MockExpenseRecordRepo) ListByVehicle(ctx context.Context, vehicleID uuid.UUID, page, pageSize int, category string, startDate, endDate *time.Time, keyword string, minAmount, maxAmount float64) ([]model.ExpenseRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVehicle", ctx, vehicleID, page, pageSize, category, startDate, endDate, keyword, minAmount, maxAmount)
	ret0, _ := ret[0].([]model.ExpenseRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByVehicle indicates an expected call of ListByVehicle.
func (mr *MockExpenseRecordRepoMockRecorder) ListByVehicle(ctx, vehicleID, page, pageSize, category, startDate, endDate, keyword, minAmount, maxAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVehicle", reflect.TypeOf((*MockExpenseRecordRepo)(nil).ListByVehicle), ctx, vehicleID, page, pageSize, category, startDate, endDate, keyword, minAmount, maxAmount)
}

// Update mocks base method.
func (m *MockExpenseRecordRepo) Update(ctx context.Context, record *model.ExpenseRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockExpenseRecordRepoMockRecorder) Update(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExpenseRecordRepo)(nil).Update), ctx, record)
}

// MockRefreshTokenRepo is a mock of RefreshTokenRepo interface.
type MockRefreshTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRepoMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRepoMockRecorder is the mock recorder for MockRefreshTokenRepo.
type MockRefreshTokenRepoMockRecorder struct {
	mock *MockRefreshTokenRepo
}

// NewMockRefreshTokenRepo creates a new mock instance.
func NewMockRefreshTokenRepo(ctrl *gomock.Controller) *MockRefreshTokenRepo {
	mock := &MockRefreshTokenRepo{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRepo) EXPECT() *MockRefreshTokenRepoMockRecorder {
	return m.recorder
}

// ConsumeByTokenHash mocks base method.
func (m *MockRefreshTokenRepo) ConsumeByTokenHash(ctx context.Context, hash string) (*model.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeByTokenHash", ctx, hash)
	ret0, _ := ret[0].(*model.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeByTokenHash indicates an expected call of ConsumeByTokenHash.
func (mr *MockRefreshTokenRepoMockRecorder) ConsumeByTokenHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeByTokenHash", reflect.TypeOf((*MockRefreshTokenRepo)(nil).ConsumeByTokenHash), ctx, hash)
}

// Create mocks base method.
func (m *MockRefreshTokenRepo) Create(ctx context.Context, token *model.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenRepoMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenRepo)(nil).Create), ctx, token)
}

// DeleteByID mocks base method.
func (m *MockRefreshTokenRepo) DeleteByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRefreshTokenRepoMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRefreshTokenRepo)(nil).DeleteByID), ctx, id)
}

// DeleteByUserID mocks base method.
func (m *MockRefreshTokenRepo) DeleteByUserID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockRefreshTokenRepoMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockRefreshTokenRepo)(nil).DeleteByUserID), ctx, userID)
}

// DeleteExpired mocks base method.
func (m *MockRefreshTokenRepo) DeleteExpired(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockRefreshTokenRepoMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockRefreshTokenRepo)(nil).DeleteExpired), ctx)
}

// GetByTokenHash mocks base method.
func (m *MockRefreshTokenRepo) GetByTokenHash(ctx context.Context, hash string) (*model.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, hash)
	ret0, _ := ret[0].(*model.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockRefreshTokenRepoMockRecorder) GetByTokenHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockRefreshTokenRepo)(nil).GetByTokenHash), ctx, hash)
}

// MockInviteCodeRepo is a mock of InviteCodeRepo interface.
type MockInviteCodeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInviteCodeRepoMockRecorder
	isgomock struct{}
}

// MockInviteCodeRepoMockRecorder is the mock recorder for MockInviteCodeRepo.
type MockInviteCodeRepoMockRecorder struct {
	mock *MockInviteCodeRepo
}

// NewMockInviteCodeRepo creates a new mock instance.
func NewMockInviteCodeRepo(ctrl *gomock.Controller) *MockInviteCodeRepo {
	mock := &MockInviteCodeRepo{ctrl: ctrl}
	mock.recorder = &MockInviteCodeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInviteCodeRepo) EXPECT() *MockInviteCodeRepoMockRecorder {
	return m.recorder
}

// ConsumeByCode mocks base method.
func (m *MockInviteCodeRepo) ConsumeByCode(ctx context.Context, code string, usedByID uuid.UUID) (*model.InviteCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeByCode", ctx, code, usedByID)
	ret0, _ := ret[0].(*model.InviteCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeByCode indicates an expected call of ConsumeByCode.
func (mr *MockInviteCodeRepoMockRecorder) ConsumeByCode(ctx, code, usedByID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeByCode", reflect.TypeOf((*MockInviteCodeRepo)(nil).ConsumeByCode), ctx, code, usedByID)
}

// Create mocks base method.
func (m *MockInviteCodeRepo) Create(ctx context.Context, invite *model.InviteCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInviteCodeRepoMockRecorder) Create(ctx, invite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInviteCodeRepo)(nil).Create), ctx, invite)
}

// Delete mocks base method.
func (m *MockInviteCodeRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInviteCodeRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInviteCodeRepo)(nil).Delete), ctx, id)
}

// ExistsByCode mocks base method.
func (m *MockInviteCodeRepo) ExistsByCode(ctx context.Context, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByCode", ctx, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByCode indicates an expected call of ExistsByCode.
func (mr *MockInviteCodeRepoMockRecorder) ExistsByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByCode", reflect.TypeOf((*MockInviteCodeRepo)(nil).ExistsByCode), ctx, code)
}

// GetByCode mocks base method.
func (m *MockInviteCodeRepo) GetByCode(ctx context.Context, code string) (*model.InviteCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*model.InviteCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockInviteCodeRepoMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockInviteCodeRepo)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockInviteCodeRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.InviteCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.InviteCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInviteCodeRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInviteCodeRepo)(nil).GetByID), ctx, id)
}

// ListByCreator mocks base method.
func (m *MockInviteCodeRepo) ListByCreator(ctx context.Context, creatorID uuid.UUID) ([]model.InviteCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCreator", ctx, creatorID)
	ret0, _ := ret[0].([]model.InviteCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCreator indicates an expected call of ListByCreator.
func (mr *MockInviteCodeRepoMockRecorder) ListByCreator(ctx, creatorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCreator", reflect.TypeOf((*MockInviteCodeRepo)(nil).ListByCreator), ctx, creatorID)
}

// Update mocks base method.
func (m *MockInviteCodeRepo) Update(ctx context.Context, invite *model.InviteCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, invite)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInviteCodeRepoMockRecorder) Update(ctx, invite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInviteCodeRepo)(nil).Update), ctx, invite)
}

// MockReminderRepo is a mock of ReminderRepo interface.
type MockReminderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockReminderRepoMockRecorder
	isgomock struct{}
}

// MockReminderRepoMockRecorder is the mock recorder for MockReminderRepo.
type MockReminderRepoMockRecorder struct {
	mock *MockReminderRepo
}

// NewMockReminderRepo creates a new mock instance.
func NewMockReminderRepo(ctrl *gomock.Controller) *MockReminderRepo {
	mock := &MockReminderRepo{ctrl: ctrl}
	mock.recorder = &MockReminderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReminderRepo) EXPECT() *MockReminderRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReminderRepo) Create(ctx context.Context, reminder *model.Reminder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reminder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReminderRepoMockRecorder) Create(ctx, reminder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReminderRepo)(nil).Create), ctx, reminder)
}

// Delete mocks base method.
func (m *MockReminderRepo) Delete(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReminderRepoMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReminderRepo)(nil).Delete), ctx, id, userID)
}

// GetByID mocks base method.
func (m *MockReminderRepo) GetByID(ctx context.Context, id uuid.UUID) (*model.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReminderRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReminderRepo)(nil).GetByID), ctx, id)
}

// GetByIDAndUser mocks base method.
func (m *MockReminderRepo) GetByIDAndUser(ctx context.Context, id, userID uuid.UUID) (*model.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDAndUser", ctx, id, userID)
	ret0, _ := ret[0].(*model.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDAndUser indicates an expected call of GetByIDAndUser.
func (mr *MockReminderRepoMockRecorder) GetByIDAndUser(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDAndUser", reflect.TypeOf((*MockReminderRepo)(nil).GetByIDAndUser), ctx, id, userID)
}

// ListByUser mocks base method.
func (m *MockReminderRepo) ListByUser(ctx context.Context, userID uuid.UUID) ([]model.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockReminderRepoMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockReminderRepo)(nil).ListByUser), ctx, userID)
}

// ListByVehicle mocks base method.
func (m *MockReminderRepo) ListByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]model.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByVehicle", ctx, vehicleID)
	ret0, _ := ret[0].([]model.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByVehicle indicates an expected call of ListByVehicle.
func (mr *MockReminderRepoMockRecorder) ListByVehicle(ctx, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByVehicle", reflect.TypeOf((*MockReminderRepo)(nil).ListByVehicle), ctx, vehicleID)
}

// ListEnabledByVehicle mocks base method.
func (m *MockReminderRepo) ListEnabledByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]model.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledByVehicle", ctx, vehicleID)
	ret0, _ := ret[0].([]model.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledByVehicle indicates an expected call of ListEnabledByVehicle.
func (mr *MockReminderRepoMockRecorder) ListEnabledByVehicle(ctx, vehicleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledByVehicle", reflect.TypeOf((*MockReminderRepo)(nil).ListEnabledByVehicle), ctx, vehicleID)
}

// Update mocks base method.
func (m *MockReminderRepo) Update(ctx context.Context, reminder *model.Reminder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, reminder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockReminderRepoMockRecorder) Update(ctx, reminder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReminderRepo)(nil).Update), ctx, reminder)
}

// MockNotificationRepo is a mock of NotificationRepo interface.
type MockNotificationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepoMockRecorder
	isgomock struct{}
}

// MockNotificationRepoMockRecorder is the mock recorder for MockNotificationRepo.
type MockNotificationRepoMockRecorder struct {
	mock *MockNotificationRepo
}

// NewMockNotificationRepo creates a new mock instance.
func NewMockNotificationRepo(ctrl *gomock.Controller) *MockNotificationRepo {
	mock := &MockNotificationRepo{ctrl: ctrl}
	mock.recorder = &MockNotificationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepo) EXPECT() *MockNotificationRepoMockRecorder {
	return m.recorder
}

// CountUnread mocks base method.
func (m *MockNotificationRepo) CountUnread(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnread", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnread indicates an expected call of CountUnread.
func (mr *MockNotificationRepoMockRecorder) CountUnread(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnread", reflect.TypeOf((*MockNotificationRepo)(nil).CountUnread), ctx, userID)
}

// Create mocks base method.
func (m *MockNotificationRepo) Create(ctx context.Context, notification *model.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationRepoMockRecorder) Create(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationRepo)(nil).Create), ctx, notification)
}

// Delete mocks base method.
func (m *MockNotificationRepo) Delete(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationRepoMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationRepo)(nil).Delete), ctx, id, userID)
}

// ListAllByUser mocks base method.
func (m *MockNotificationRepo) ListAllByUser(ctx context.Context, userID uuid.UUID) ([]model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllByUser indicates an expected call of ListAllByUser.
func (mr *MockNotificationRepoMockRecorder) ListAllByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllByUser", reflect.TypeOf((*MockNotificationRepo)(nil).ListAllByUser), ctx, userID)
}

// ListByUser mocks base method.
func (m *MockNotificationRepo) ListByUser(ctx context.Context, userID uuid.UUID, limit int) ([]model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, limit)
	ret0, _ := ret[0].([]model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockNotificationRepoMockRecorder) ListByUser(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockNotificationRepo)(nil).ListByUser), ctx, userID, limit)
}

// MarkAllAsRead mocks base method.
func (m *MockNotificationRepo) MarkAllAsRead(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllAsRead", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllAsRead indicates an expected call of MarkAllAsRead.
func (mr *MockNotificationRepoMockRecorder) MarkAllAsRead(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllAsRead", reflect.TypeOf((*MockNotificationRepo)(nil).MarkAllAsRead), ctx, userID)
}

// MarkAsRead mocks base method.
func (m *MockNotificationRepo) MarkAsRead(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockNotificationRepoMockRecorder) MarkAsRead(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockNotificationRepo)(nil).MarkAsRead), ctx, id, userID)
}
